name: Just-ssh
on:
  push:
    branches: ["delete-files-test"]

jobs:
  ssh-into:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - id: changed-files
      name: Get changed files
      uses: tj-actions/changed-files@v18.4
    
    - name: Zipping and copying to the destination
      env:
        SSH_KEY: ${{ secrets.STAGE_KEY }}
        LIVE_USER: ${{ secrets.STAGE_USERNAME }}
        HOST: ${{ secrets.STAGE_HOST }}
        PORT: ${{ secrets.STAGE_PORT }}
        DEST: ${{ secrets.STAGE_SCP_URL }}
      run: |
        echo -e "${SSH_KEY}" > keyfile
        chmod 600 keyfile
        zip -qq -r archive.zip *
        scp -o StrictHostKeyChecking=no -P $PORT -i keyfile archive.zip $LIVE_USER@$HOST:$DEST

    - name: Deploying artifacts on dihk-stage
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.STAGE_HOST }}
        username: ${{ secrets.STAGE_USERNAME }}
        key: ${{ secrets.STAGE_KEY }}
        port: ${{ secrets.STAGE_PORT }}
        DEST: ${{ secrets.STAGE_SCP_URL }}
        script_stop: true
        command_timeout: 15m
        script: |
          unzip -qq -o /home/pmuser/delete-files-test/archive.zip -d /home/pmuser/delete-files-test


    - name: Delete deleted files from server
      env:        
        SSH_KEY: ${{ secrets.STAGE_KEY }}
        HOST: ${{ secrets.STAGE_HOST }}
        USERNAME: ${{ secrets.STAGE_USERNAME }}
        PORT: ${{ secrets.STAGE_PORT }}
      run: |
        mkdir -p ~/.ssh 
        echo -e "${SSH_KEY}" >~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "All modified files are: ${{ steps.changed-files.outputs.all_modified_files }}"
        for file in ${{ steps.changed-files.outputs.deleted_files }}; do
          if [ ! -z $file ]
            then
              ssh -p $PORT $USERNAME@$HOST "cd /home/pmuser/delete-files-test/sub && rm ${{ steps.changed-files.outputs.deleted_files }}"
              for file in ${{ steps.changed-files.outputs.deleted_files }}; do
                echo "$file was deleted from the server"
              done
            break
          fi
        done