--- 
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v3
        with: 
          fetch-depth: 1
      - 
        id: changed-files
        name: "Get changed files"
        uses: tj-actions/changed-files@v18.4
      - 
        env: 
          DEST: "${{ secrets.STAGE_SCP_URL }}"
          HOST: "${{ secrets.STAGE_HOST }}"
          LIVE_USER: "${{ secrets.STAGE_USERNAME }}"
          PORT: "${{ secrets.STAGE_PORT }}"
          SSH_KEY: "${{ secrets.STAGE_KEY }}"
        name: "Creating artifacts and scp to dihk-stage"
        run: |
            cd src/public
            echo -e "${SSH_KEY}" >keyfile
            chmod 600 keyfile
            zip -qq -r archive.zip *
            scp -o StrictHostKeyChecking=no -P $PORT -i keyfile archive.zip $DEST
      - 
        name: "Deploying artifacts on dihk-stage"
        uses: appleboy/ssh-action@master
        with: 
          command_timeout: 15m
          host: "${{ secrets.STAGE_HOST }}"
          key: "${{ secrets.STAGE_KEY }}"
          port: "${{ secrets.STAGE_PORT }}"
          script: "unzip -qq -o archive.zip -d /home/pmuser/delete-files-test\n"
          script_stop: true
          username: "${{ secrets.STAGE_USERNAME }}"
      - 
        env: 
          HOST: "${{ secrets.STAGE_HOST }}"
          PORT: "${{ secrets.STAGE_PORT }}"
          SSH_KEY: "${{ secrets.STAGE_KEY }}"
          USERNAME: "${{ secrets.STAGE_USERNAME }}"
        name: "Delete deleted files from server"
        run: |
            mkdir -p ~/.ssh 
            echo -e "${SSH_KEY}" >~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            for file in ${{ steps.changed-files.outputs.deleted_files }}; do
              if [ ! -z $file ]
                then
                  ssh -p $PORT $USERNAME@$HOST "cd /home/pmuser/delete-files-test && rm ${{ steps.changed-files.outputs.deleted_files }}"
                  for file in ${{ steps.changed-files.outputs.deleted_files }}; do
                    echo "$file was deleted from the server"
                  done
                break
              fi
            done
name: Stage
true: 
  push: 
    branches: 
      - delete-files-test
